[package]
name = "starpdf"
version = "0.1.0"
edition = "2021"
authors = ["ToolRakyat Core Engineering"]
description = "Low-level, zero-dependency, high-performance PDF engine."
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
miniz_oxide = "0.9.1"
wasm-bindgen = { version = "0.2.100", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }
unicode-bidi = "0.3.18"

[features]
default = []
wasm = ["wasm-bindgen", "serde", "serde-wasm-bindgen"]

[dev-dependencies]

[[bench]]
name = "benchmark_main"
harness = false
