[package]
name = "starpdf"
version = "0.1.0"
edition = "2021"
authors = ["ToolRakyat Core Engineering"]
description = "Low-level, zero-dependency, high-performance PDF engine."
license = "MIT OR Apache-2.0"

[dependencies]
# Intentionally 0 external dependencies for core engine runtime.
# Standard library is used exclusively for performance, security, and portability.

[dev-dependencies]

[[bench]]
name = "benchmark_main"
harness = false
