#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Integer(i64),
    Real(f64),
    Name(String),
    LiteralString(Vec<u8>),
    HexString(Vec<u8>),
    Boolean(bool),
    Null,
    ArrayOpen,
    ArrayClose,
    DictOpen,
    DictClose,
    KeywordR,
    KeywordObj,
    KeywordEndObj,
    KeywordStream,
    KeywordEndStream,
    KeywordXref,
    KeywordTrailer,
    KeywordStartXref,
    Keyword(String),
    Comment(Vec<u8>),
}
