import type { ToolCategoryId, ToolDefinition } from "@/lib/tools/types";
import { TOOL_CATEGORIES } from "@/lib/tools/types";

const DEFAULT_PRIVACY_NOTE =
  "Files are processed temporarily and auto-deleted after processing. We do not permanently store uploads by default.";

export const tools: ToolDefinition[] = [
  // PDF
  {
    id: "pdf-merge",
    name: "Merge PDF",
    slug: "merge",
    categoryId: "pdf",
    category: "PDF",
    description: "Combine multiple PDF files into one.",
    icon: "Files",
    tags: ["pdf", "merge", "combine"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/pdf/merge",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Merge PDF Online Free",
    seoDescription:
      "Combine multiple PDF files into one PDF for free. Fast, simple, privacy-friendly PDF merging.",
  },
  {
    id: "pdf-split",
    name: "Split PDF",
    slug: "split",
    categoryId: "pdf",
    category: "PDF",
    description: "Split a PDF into multiple files or extract page ranges.",
    icon: "Scissors",
    tags: ["pdf", "split", "extract"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/pdf/split",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Split PDF Online Free",
    seoDescription:
      "Split a PDF by pages or ranges for free. Download a ZIP of results with privacy-first processing.",
  },
  {
    id: "pdf-rotate",
    name: "Rotate PDF",
    slug: "rotate",
    categoryId: "pdf",
    category: "PDF",
    description: "Rotate pages in a PDF by 90/180/270 degrees.",
    icon: "RotateCw",
    tags: ["pdf", "rotate", "pages"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/pdf/rotate",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Rotate PDF Online Free",
    seoDescription:
      "Rotate PDF pages for free. Rotate all pages or selected pages with privacy-friendly processing.",
  },
  {
    id: "pdf-images-to-pdf",
    name: "Images to PDF",
    slug: "images-to-pdf",
    categoryId: "pdf",
    category: "PDF",
    description: "Convert JPG/PNG/WebP images into a PDF.",
    icon: "ImagePlus",
    tags: ["pdf", "images", "convert"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/pdf/images-to-pdf",
    acceptedFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 25,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Images to PDF Online Free",
    seoDescription:
      "Turn images into a PDF for free. Simple, fast, privacy-first conversion.",
  },
  {
    id: "pdf-delete-pages",
    name: "Delete PDF Pages",
    slug: "delete-pages",
    categoryId: "pdf",
    category: "PDF",
    description: "Remove specific pages from a PDF by page ranges.",
    icon: "Trash2",
    tags: ["pdf", "delete", "pages"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/pdf/delete-pages",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Delete PDF Pages Online Free",
    seoDescription:
      "Delete pages from a PDF for free using page ranges like 1-3,5,8. Privacy-first processing.",
  },
  {
    id: "pdf-extract-pages",
    name: "Extract PDF Pages",
    slug: "extract-pages",
    categoryId: "pdf",
    category: "PDF",
    description: "Extract specific pages from a PDF into a new PDF.",
    icon: "FileOutput",
    tags: ["pdf", "extract", "pages"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/pdf/extract-pages",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Extract PDF Pages Online Free",
    seoDescription:
      "Extract pages from a PDF for free using ranges like 1-3,5,8. Fast and privacy-friendly.",
  },
  {
    id: "pdf-page-numbers",
    name: "Add Page Numbers",
    slug: "page-numbers",
    categoryId: "pdf",
    category: "PDF",
    description: "Add page numbers to a PDF with position and formatting options.",
    icon: "Hash",
    tags: ["pdf", "page numbers", "numbering"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/pdf/page-numbers",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Add Page Numbers to PDF Online Free",
    seoDescription:
      "Add page numbers to a PDF for free. Choose position, start number, and prefix/suffix.",
  },
  {
    id: "pdf-watermark",
    name: "Add Watermark",
    slug: "watermark",
    categoryId: "pdf",
    category: "PDF",
    description: "Add a text watermark to every page of a PDF.",
    icon: "Stamp",
    tags: ["pdf", "watermark", "text"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/pdf/watermark",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Add Watermark to PDF Online Free",
    seoDescription:
      "Add a text watermark to a PDF for free. Control opacity, size, rotation, and tiling.",
  },
  {
    id: "pdf-metadata",
    name: "PDF Metadata Editor",
    slug: "metadata",
    categoryId: "pdf",
    category: "PDF",
    description: "Edit PDF metadata fields like title, author, and keywords.",
    icon: "Info",
    tags: ["pdf", "metadata", "title", "author"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/pdf/metadata",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "PDF Metadata Editor Online Free",
    seoDescription:
      "Edit PDF metadata for free: title, author, subject, keywords, and creator (producer when supported).",
  },
  {
    id: "pdf-sign",
    name: "Sign PDF",
    slug: "sign",
    categoryId: "pdf",
    category: "PDF",
    description: "Place a signature image on a PDF page.",
    icon: "PenTool",
    tags: ["pdf", "sign", "signature"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/pdf/sign",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Sign PDF Online Free",
    seoDescription:
      "Sign a PDF for free by placing a signature image on a chosen page and position.",
  },

  {
    id: "pdf-reorder",
    name: "Reorder PDF Pages",
    slug: "reorder",
    categoryId: "pdf",
    category: "PDF",
    description: "Reorder pages in a PDF by specifying a new page sequence.",
    icon: "ArrowUpDown",
    tags: ["pdf", "reorder", "pages", "organize"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/pdf/reorder",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Reorder PDF Pages Online Free",
    seoDescription:
      "Reorder pages in your PDF for free. Specify a custom page order like 3,1,2 and download the reordered PDF.",
  },
  {
    id: "pdf-editor",
    name: "Advanced PDF Editor",
    slug: "editor",
    categoryId: "pdf",
    category: "PDF",
    description: "Professional intelligence-driven PDF editor with OCR, structural analysis, table extraction, and true content editing.",
    icon: "SquarePen",
    tags: ["pdf", "editor", "smart", "ocr", "extract tables", "edit text", "sign"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/pdf/editor",
    acceptedFileTypes: ["application/pdf"],
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Professional Smart PDF Editor | ToolRakyat",
    seoDescription:
      "Edit PDF content with intelligence. OCR scanned pages, extract tables, replace text, and export structure with ToolRakyat's professional-grade smart engine.",
  },

  // Image
  {
    id: "image-compress",
    name: "Compress Image",
    slug: "compress",
    categoryId: "image",
    category: "Image",
    description: "Reduce image file size while keeping quality.",
    icon: "Shrink",
    tags: ["image", "compress", "jpg", "png", "webp"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/image/compress",
    acceptedFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 25,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Compress Image Online Free",
    seoDescription:
      "Compress JPG/PNG/WebP images for free. Fast, privacy-friendly processing.",
  },
  {
    id: "image-resize",
    name: "Resize Image",
    slug: "resize",
    categoryId: "image",
    category: "Image",
    description: "Resize images to exact dimensions with aspect ratio options.",
    icon: "Scan",
    tags: ["image", "resize"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/image/resize",
    acceptedFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 25,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Resize Image Online Free",
    seoDescription:
      "Resize images for free with privacy-first processing and fast downloads.",
  },
  {
    id: "image-convert",
    name: "Convert Image",
    slug: "convert",
    categoryId: "image",
    category: "Image",
    description: "Convert images between JPG, PNG, WebP, and AVIF formats.",
    icon: "Repeat2",
    tags: ["image", "convert", "jpg", "png", "webp", "avif"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/image/convert",
    acceptedFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 25,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Convert Image Online Free",
    seoDescription:
      "Convert images for free (JPG, PNG, WebP, AVIF). Fast, simple, privacy-first processing.",
  },
  {
    id: "image-rotate",
    name: "Rotate Image",
    slug: "rotate",
    categoryId: "image",
    category: "Image",
    description: "Rotate images by 90, 180, or 270 degrees.",
    icon: "RotateCw",
    tags: ["image", "rotate"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/image/rotate",
    acceptedFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 25,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Rotate Image Online Free",
    seoDescription:
      "Rotate images for free. Fast and privacy-friendly processing.",
  },
  {
    id: "image-flip",
    name: "Flip Image",
    slug: "flip",
    categoryId: "image",
    category: "Image",
    description: "Flip images horizontally or vertically.",
    icon: "FlipHorizontal2",
    tags: ["image", "flip", "mirror"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/image/flip",
    acceptedFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 25,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Flip Image Online Free",
    seoDescription:
      "Flip images horizontally or vertically for free with privacy-first processing.",
  },
  {
    id: "image-remove-metadata",
    name: "Remove Image Metadata",
    slug: "remove-metadata",
    categoryId: "image",
    category: "Image",
    description: "Strip EXIF and common metadata from an image.",
    icon: "Eraser",
    tags: ["image", "metadata", "exif", "privacy"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/image/remove-metadata",
    acceptedFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 25,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Remove Image Metadata Online Free",
    seoDescription:
      "Strip image metadata (EXIF) for free. Privacy-friendly processing and fast download.",
  },

  // Compression
  {
    id: "compression-batch-image-compress",
    name: "Image Batch Compressor",
    slug: "batch-image-compress",
    categoryId: "compression",
    category: "Compression",
    description: "Compress many images at once and download as a ZIP.",
    icon: "Layers",
    tags: ["image", "compress", "batch", "zip"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/compression/batch-image-compress",
    acceptedFileTypes: ["image/jpeg", "image/png", "image/webp"],
    maxFileSizeMB: 25,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Batch Compress Images Online Free",
    seoDescription:
      "Compress multiple images for free and download a ZIP. Fast, privacy-first processing.",
  },
  {
    id: "zip-create",
    name: "ZIP Creator",
    slug: "zip",
    categoryId: "compression",
    category: "Compression",
    description: "Create a ZIP archive from multiple files.",
    icon: "Archive",
    tags: ["zip", "compress", "archive"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/compression/zip",
    maxFileSizeMB: 50,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Create ZIP Online Free",
    seoDescription:
      "Create a ZIP file for free. Upload files, download a single archive. Privacy-first.",
  },
  {
    id: "compression-json-minifier",
    name: "JSON Minifier",
    slug: "json-minifier",
    categoryId: "compression",
    category: "Compression",
    description: "Minify JSON by removing whitespace.",
    icon: "Braces",
    tags: ["json", "minify", "compression"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/compression/json-minifier",
    privacyNote: "Runs locally in your browser. We never upload your JSON.",
    seoTitle: "JSON Minifier Online Free",
    seoDescription:
      "Minify JSON for free. Validate and compress JSON by removing whitespace. Runs locally for privacy.",
  },
  {
    id: "compression-css-minifier",
    name: "CSS Minifier",
    slug: "css-minifier",
    categoryId: "compression",
    category: "Compression",
    description: "Minify CSS by removing comments and unnecessary whitespace.",
    icon: "FileText",
    tags: ["css", "minify", "compression"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/compression/css-minifier",
    privacyNote: "Runs locally in your browser. We never upload your CSS.",
    seoTitle: "CSS Minifier Online Free",
    seoDescription:
      "Minify CSS for free. Remove comments and whitespace locally in your browser for privacy.",
  },
  {
    id: "compression-html-minifier",
    name: "HTML Minifier",
    slug: "html-minifier",
    categoryId: "compression",
    category: "Compression",
    description: "Minify HTML by removing comments and collapsing whitespace.",
    icon: "FileText",
    tags: ["html", "minify", "compression"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/compression/html-minifier",
    privacyNote: "Runs locally in your browser. We never upload your HTML.",
    seoTitle: "HTML Minifier Online Free",
    seoDescription:
      "Minify HTML for free. Remove comments and whitespace locally in your browser for privacy.",
  },
  {
    id: "zip-extract",
    name: "ZIP Extractor",
    slug: "zip-extract",
    categoryId: "compression",
    category: "Compression",
    description: "Extract a ZIP archive safely and download extracted files.",
    icon: "FolderDown",
    tags: ["zip", "extract", "unzip"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/compression/zip-extract",
    acceptedFileTypes: ["application/zip"],
    maxFileSizeMB: 100,
    privacyNote: DEFAULT_PRIVACY_NOTE,
    seoTitle: "Extract ZIP Online Free",
    seoDescription:
      "Extract ZIP files for free with safe handling and privacy-first processing.",
  },

  // Converter
  {
    id: "converter-csv-to-json",
    name: "CSV to JSON",
    slug: "csv-to-json",
    categoryId: "converter",
    category: "Converter",
    description: "Convert CSV data into JSON.",
    icon: "ArrowLeftRight",
    tags: ["csv", "json", "convert"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/converter/csv-to-json",
    seoTitle: "CSV to JSON Online Free",
    seoDescription:
      "Convert CSV to JSON for free. Runs locally in your browser when possible.",
  },
  {
    id: "converter-json-to-csv",
    name: "JSON to CSV",
    slug: "json-to-csv",
    categoryId: "converter",
    category: "Converter",
    description: "Convert JSON arrays/objects into CSV.",
    icon: "ArrowLeftRight",
    tags: ["json", "csv", "convert"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/converter/json-to-csv",
    seoTitle: "JSON to CSV Online Free",
    seoDescription:
      "Convert JSON to CSV for free. Runs locally in your browser for privacy.",
  },
  {
    id: "converter-markdown-to-html",
    name: "Markdown to HTML",
    slug: "markdown-to-html",
    categoryId: "converter",
    category: "Converter",
    description: "Convert Markdown into sanitized HTML.",
    icon: "FileText",
    tags: ["markdown", "html", "convert"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/converter/markdown-to-html",
    seoTitle: "Markdown to HTML Online Free",
    seoDescription:
      "Convert Markdown to HTML for free with a sanitized preview. Runs locally in your browser.",
  },

  // Text (we’ll implement Word Counter early)
  {
    id: "text-word-counter",
    name: "Word Counter",
    slug: "word-counter",
    categoryId: "text",
    category: "Text",
    description:
      "Count words, characters, sentences, paragraphs, and reading time.",
    icon: "Type",
    tags: ["text", "words", "counter"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/text/word-counter",
    seoTitle: "Word Counter Online Free",
    seoDescription:
      "Count words and characters for free. Fast, simple, privacy-friendly word counter.",
  },
  {
    id: "text-slug-generator",
    name: "Slug Generator",
    slug: "slug-generator",
    categoryId: "text",
    category: "Text",
    description: "Turn titles into clean SEO-friendly slugs.",
    icon: "Link2",
    tags: ["text", "slug", "seo"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/text/slug-generator",
    seoTitle: "Slug Generator Online Free",
    seoDescription:
      "Generate SEO-friendly slugs for free. Runs locally in your browser.",
  },
  {
    id: "text-case-converter",
    name: "Case Converter",
    slug: "case-converter",
    categoryId: "text",
    category: "Text",
    description:
      "Convert text to uppercase, lowercase, title case, kebab-case, snake_case, and more.",
    icon: "Type",
    tags: ["text", "case", "convert"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/text/case-converter",
    seoTitle: "Case Converter Online Free",
    seoDescription:
      "Convert text casing for free: uppercase, lowercase, title case, sentence case, kebab-case, snake_case, camelCase.",
  },
  {
    id: "text-cleaner",
    name: "Text Cleaner",
    slug: "text-cleaner",
    categoryId: "text",
    category: "Text",
    description: "Clean text by trimming lines, removing spaces, and more.",
    icon: "FileText",
    tags: ["text", "clean", "spaces"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/text/text-cleaner",
    seoTitle: "Text Cleaner Online Free",
    seoDescription:
      "Clean text for free: trim lines, remove extra spaces, remove empty lines, remove duplicates.",
  },
  {
    id: "text-password-generator",
    name: "Password Generator",
    slug: "password-generator",
    categoryId: "text",
    category: "Text",
    description: "Generate random passwords with selectable character sets.",
    icon: "Hash",
    tags: ["password", "random", "security"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/text/password-generator",
    seoTitle: "Password Generator Online Free",
    seoDescription:
      "Generate secure random passwords for free with length and character options. Runs locally in your browser.",
  },

  // Business
  {
    id: "business-invoice",
    name: "Invoice Generator",
    slug: "invoice-generator",
    categoryId: "business",
    category: "Business",
    description: "Create a simple invoice and download as PDF.",
    icon: "Receipt",
    tags: ["invoice", "pdf", "sme"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/business/invoice-generator",
    seoTitle: "Invoice Generator Online Free",
    seoDescription:
      "Generate a simple invoice PDF for free. Fast, clean, privacy-first.",
  },
  {
    id: "business-quotation",
    name: "Quotation Generator",
    slug: "quotation-generator",
    categoryId: "business",
    category: "Business",
    description: "Create a quotation and download as PDF.",
    icon: "FileText",
    tags: ["quotation", "quote", "pdf", "sme"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/business/quotation-generator",
    seoTitle: "Quotation Generator Online Free",
    seoDescription:
      "Generate a quotation PDF for free with validity date and clean formatting.",
  },
  {
    id: "business-receipt",
    name: "Receipt Generator",
    slug: "receipt-generator",
    categoryId: "business",
    category: "Business",
    description: "Create a simple receipt and download as PDF.",
    icon: "Receipt",
    tags: ["receipt", "pdf", "sme"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/business/receipt-generator",
    seoTitle: "Receipt Generator Online Free",
    seoDescription:
      "Generate a simple receipt PDF for free. Fast, clean, and professional.",
  },
  {
    id: "business-delivery-order",
    name: "Delivery Order Generator",
    slug: "delivery-order-generator",
    categoryId: "business",
    category: "Business",
    description: "Create a delivery order and download as PDF.",
    icon: "Truck",
    tags: ["delivery order", "do", "pdf", "sme"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/business/delivery-order-generator",
    seoTitle: "Delivery Order Generator Online Free",
    seoDescription:
      "Generate a delivery order PDF for free. Clean formatting for logistics and SME needs.",
  },
  {
    id: "business-purchase-order",
    name: "Purchase Order Generator",
    slug: "purchase-order-generator",
    categoryId: "business",
    category: "Business",
    description: "Create a purchase order and download as PDF.",
    icon: "ShoppingCart",
    tags: ["purchase order", "po", "pdf", "sme"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/business/purchase-order-generator",
    seoTitle: "Purchase Order Generator Online Free",
    seoDescription:
      "Generate a purchase order PDF for free. Fast, professional PO generation for your business.",
  },

  // Calculator
  {
    id: "calc-loan",
    name: "Loan Calculator",
    slug: "loan",
    categoryId: "calculator",
    category: "Calculator",
    description: "Calculate monthly payments from principal, rate, and term.",
    icon: "Calculator",
    tags: ["calculator", "loan", "finance"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/calculator/loan",
    seoTitle: "Loan Calculator Online Free",
    seoDescription:
      "Calculate loan monthly payments for free with clear formula explanations.",
  },
  {
    id: "calc-profit-margin",
    name: "Profit Margin Calculator",
    slug: "profit-margin",
    categoryId: "calculator",
    category: "Calculator",
    description: "Calculate profit and profit margin percentage.",
    icon: "Calculator",
    tags: ["calculator", "profit", "margin"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/calculator/profit-margin",
    seoTitle: "Profit Margin Calculator Online Free",
    seoDescription:
      "Calculate profit and profit margin for free. Clear formulas and instant results.",
  },
  {
    id: "calc-discount",
    name: "Discount Calculator",
    slug: "discount",
    categoryId: "calculator",
    category: "Calculator",
    description: "Calculate discount amount and final price.",
    icon: "Calculator",
    tags: ["calculator", "discount", "sale"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/calculator/discount",
    seoTitle: "Discount Calculator Online Free",
    seoDescription:
      "Calculate discounts for free. Get final price and discount amount instantly.",
  },
  {
    id: "calc-sst",
    name: "SST Calculator",
    slug: "sst",
    categoryId: "calculator",
    category: "Calculator",
    description: "Calculate SST amount and total.",
    icon: "Calculator",
    tags: ["calculator", "sst", "tax"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/calculator/sst",
    seoTitle: "SST Calculator Online Free",
    seoDescription:
      "Calculate SST for free. Enter amount and rate to get SST and total.",
  },
  {
    id: "calc-age",
    name: "Age Calculator",
    slug: "age",
    categoryId: "calculator",
    category: "Calculator",
    description: "Calculate age in years from a birth date.",
    icon: "Calculator",
    tags: ["calculator", "age", "date"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/calculator/age",
    seoTitle: "Age Calculator Online Free",
    seoDescription:
      "Calculate age for free using birth date and an optional 'as of' date.",
  },
  {
    id: "calc-date-difference",
    name: "Date Difference Calculator",
    slug: "date-difference",
    categoryId: "calculator",
    category: "Calculator",
    description: "Calculate the number of days between two dates.",
    icon: "Calculator",
    tags: ["calculator", "date", "difference"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/calculator/date-difference",
    seoTitle: "Date Difference Calculator Online Free",
    seoDescription:
      "Calculate date difference in days for free. Simple and fast.",
  },
  {
    id: "calc-bmi",
    name: "BMI Calculator",
    slug: "bmi",
    categoryId: "calculator",
    category: "Calculator",
    description: "Calculate Body Mass Index (BMI) and category.",
    icon: "Calculator",
    tags: ["calculator", "bmi", "health"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/calculator/bmi",
    seoTitle: "BMI Calculator Online Free",
    seoDescription:
      "Calculate BMI for free with weight (kg) and height (cm).",
  },
  {
    id: "calc-compound-interest",
    name: "Compound Interest Calculator",
    slug: "compound-interest",
    categoryId: "calculator",
    category: "Calculator",
    description: "Calculate future value with compound interest.",
    icon: "Calculator",
    tags: ["calculator", "interest", "compound"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/calculator/compound-interest",
    seoTitle: "Compound Interest Calculator Online Free",
    seoDescription:
      "Calculate compound interest for free. Enter principal, rate, years, and compounding frequency.",
  },

  // Developer
  {
    id: "dev-json-formatter",
    name: "JSON Formatter",
    slug: "json-formatter",
    categoryId: "developer",
    category: "Developer",
    description: "Format and validate JSON locally in your browser.",
    icon: "Braces",
    tags: ["developer", "json", "format"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/developer/json-formatter",
    seoTitle: "JSON Formatter Online Free",
    seoDescription:
      "Format and validate JSON for free. Runs locally — we never upload your JSON.",
  },
  {
    id: "dev-json-validator",
    name: "JSON Validator",
    slug: "json-validator",
    categoryId: "developer",
    category: "Developer",
    description: "Validate JSON locally (no upload).",
    icon: "Braces",
    tags: ["developer", "json", "validate"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/developer/json-validator",
    seoTitle: "JSON Validator Online Free",
    seoDescription:
      "Validate JSON for free. Runs locally — we never upload your JSON.",
  },
  {
    id: "dev-base64",
    name: "Base64 Encode/Decode",
    slug: "base64",
    categoryId: "developer",
    category: "Developer",
    description: "Encode or decode Base64 strings locally.",
    icon: "FileText",
    tags: ["developer", "base64", "encode", "decode"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/developer/base64",
    seoTitle: "Base64 Encode/Decode Online Free",
    seoDescription:
      "Encode and decode Base64 for free. Runs locally in your browser for privacy.",
  },
  {
    id: "dev-url-encode",
    name: "URL Encode/Decode",
    slug: "url-encode",
    categoryId: "developer",
    category: "Developer",
    description: "URL encode or decode text locally.",
    icon: "Link2",
    tags: ["developer", "url", "encode", "decode"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/developer/url-encode",
    seoTitle: "URL Encode/Decode Online Free",
    seoDescription:
      "URL encode and decode for free. Runs locally in your browser for privacy.",
  },
  {
    id: "dev-sha-256",
    name: "SHA-256 Hash Generator",
    slug: "sha-256",
    categoryId: "developer",
    category: "Developer",
    description: "Generate SHA-256 hashes locally.",
    icon: "Hash",
    tags: ["developer", "hash", "sha-256"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/developer/sha-256",
    seoTitle: "SHA-256 Hash Generator Online Free",
    seoDescription:
      "Generate SHA-256 hashes for free. Runs locally in your browser for privacy.",
  },
  {
    id: "dev-uuid-generator",
    name: "UUID Generator",
    slug: "uuid-generator",
    categoryId: "developer",
    category: "Developer",
    description: "Generate UUIDs locally.",
    icon: "Hash",
    tags: ["developer", "uuid"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/developer/uuid-generator",
    seoTitle: "UUID Generator Online Free",
    seoDescription:
      "Generate UUIDs for free. Runs locally in your browser.",
  },
  {
    id: "dev-color-converter",
    name: "HEX/RGB Color Converter",
    slug: "color-converter",
    categoryId: "developer",
    category: "Developer",
    description: "Convert colors between HEX and RGB.",
    icon: "FileText",
    tags: ["developer", "color", "hex", "rgb"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/developer/color-converter",
    seoTitle: "HEX to RGB Converter Online Free",
    seoDescription:
      "Convert HEX to RGB and RGB to HEX for free. Runs locally in your browser.",
  },

  // QR
  {
    id: "qr-qr-code-generator",
    name: "QR Code Generator",
    slug: "qr-code-generator",
    categoryId: "qr",
    category: "QR",
    description: "Generate a QR code for text or a URL.",
    icon: "QrCode",
    tags: ["qr", "qrcode", "generator"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/qr/qr-code-generator",
    privacyNote: "Runs locally in your browser. We never upload your text.",
    seoTitle: "QR Code Generator Online Free",
    seoDescription:
      "Generate QR codes for free. Fast and privacy-friendly.",
  },
  {
    id: "qr-whatsapp-link-generator",
    name: "WhatsApp Link Generator",
    slug: "whatsapp-link-generator",
    categoryId: "qr",
    category: "QR",
    description: "Create a wa.me link and QR code for WhatsApp chats.",
    icon: "MessageCircle",
    tags: ["whatsapp", "wa.me", "qr", "link"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/qr/whatsapp-link-generator",
    privacyNote: "Runs locally in your browser. We never upload your phone/message.",
    seoTitle: "WhatsApp Link + QR Generator Online Free",
    seoDescription:
      "Generate WhatsApp wa.me links and QR codes for free. Fast and privacy-friendly.",
  },
  {
    id: "qr-wifi",
    name: "WiFi QR Generator",
    slug: "wifi",
    categoryId: "qr",
    category: "QR",
    description: "Generate a QR code for WiFi network connection.",
    icon: "Wifi",
    tags: ["qr", "wifi", "network"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/qr/wifi",
    privacyNote: "Runs locally in your browser. We never upload your WiFi credentials.",
    seoTitle: "WiFi QR Code Generator Online Free",
    seoDescription:
      "Generate WiFi QR codes for free. Let guests connect to your network easily.",
  },
  {
    id: "qr-vcard",
    name: "vCard QR Generator",
    slug: "vcard",
    categoryId: "qr",
    category: "QR",
    description: "Generate a QR code for a contact (vCard).",
    icon: "User",
    tags: ["qr", "vcard", "contact"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/qr/vcard",
    privacyNote: "Runs locally in your browser. We never upload your contact info.",
    seoTitle: "vCard QR Code Generator Online Free",
    seoDescription:
      "Generate vCard QR codes for free. Share your contact details quickly.",
  },
  {
    id: "qr-email",
    name: "Email QR Generator",
    slug: "email",
    categoryId: "qr",
    category: "QR",
    description: "Generate a QR code to send an email.",
    icon: "Mail",
    tags: ["qr", "email"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/qr/email",
    privacyNote: "Runs locally in your browser. We never upload your email content.",
    seoTitle: "Email QR Code Generator Online Free",
    seoDescription:
      "Generate email QR codes for free. Pre-fill recipient, subject, and body.",
  },
  {
    id: "qr-sms",
    name: "SMS QR Generator",
    slug: "sms",
    categoryId: "qr",
    category: "QR",
    description: "Generate a QR code to send an SMS.",
    icon: "MessageSquare",
    tags: ["qr", "sms"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/qr/sms",
    privacyNote: "Runs locally in your browser. We never upload your SMS content.",
    seoTitle: "SMS QR Code Generator Online Free",
    seoDescription:
      "Generate SMS QR codes for free. Pre-fill recipient and message.",
  },

  // AI (UI/adapter only)
  {
    id: "ai-text-summarizer",
    name: "Text Summarizer (AI)",
    slug: "text-summarizer",
    categoryId: "ai",
    category: "AI",
    description:
      "Summarize text with an AI provider. Requires provider setup.",
    icon: "Sparkles",
    tags: ["ai", "summarize", "text"],
    isImplemented: false,
    isPopular: false,
    route: "/tools/ai/text-summarizer",
    seoTitle: "AI Text Summarizer",
    seoDescription:
      "Summarize text using an AI provider. ToolRakyat supports clean provider abstraction and honest setup requirements.",
  },

  // AkaunKemas
  {
    id: "akaunkemas-bank-csv-cleaner",
    name: "Bank CSV Cleaner",
    slug: "bank-csv-cleaner",
    categoryId: "akaunkemas",
    category: "AkaunKemas",
    description:
      "Upload a bank CSV, auto-detect columns, categorise transactions, and export a cleaned CSV, summary JSON, or accountant-ready PDF.",
    icon: "FileSpreadsheet",
    tags: ["csv", "bank", "sme", "bookkeeping", "akaunkemas", "export", "pdf"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/akaunkemas/bank-csv-cleaner",
    acceptedFileTypes: ["text/csv"],
    maxFileSizeMB: 25,
    privacyNote:
      "Files under 5MB are processed locally in your browser. Larger files may be processed through a secure server route for performance. Uploaded bank CSV files are never stored.",
    seoTitle: "Bank CSV Cleaner — AkaunKemas | ToolRakyat",
    seoDescription:
      "Clean and categorise bank CSV statements for SME monthly closing. Auto-detect columns, assign categories, export cleaned CSV, summary JSON, or accountant-ready PDF.",
  },
  {
    id: "akaunkemas-receipt-organizer",
    name: "Receipt Organizer",
    slug: "receipt-organizer",
    categoryId: "akaunkemas",
    category: "AkaunKemas",
    description: "Manually organise and categorise receipts with date, merchant, amount, payment method, and export to CSV, JSON, or PDF.",
    icon: "Receipt",
    tags: ["receipt", "sme", "bookkeeping", "akaunkemas", "export", "pdf"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/akaunkemas/receipt-organizer",
    acceptedFileTypes: ["text/csv", "application/json"],
    maxFileSizeMB: 25,
    privacyNote: "All receipt data is processed locally in your browser. Uploaded receipt images are never stored or transmitted.",
    seoTitle: "Receipt Organizer — AkaunKemas | ToolRakyat",
    seoDescription: "Organise SME receipts manually with bilingual categories. Export receipt CSV, JSON, or summary PDF for accountant submission.",
  },
  {
    id: "akaunkemas-receipt-matcher",
    name: "Receipt Matcher",
    slug: "receipt-matcher",
    categoryId: "akaunkemas",
    category: "AkaunKemas",
    description: "Match bank transactions with receipt records by amount and date window. Export matched and unmatched reports.",
    icon: "GitMerge",
    tags: ["receipt", "match", "bank", "reconciliation", "akaunkemas"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/akaunkemas/receipt-matcher",
    acceptedFileTypes: ["text/csv", "application/json"],
    maxFileSizeMB: 25,
    privacyNote: "All matching is performed locally in your browser. No data is uploaded or stored.",
    seoTitle: "Receipt Matcher — AkaunKemas | ToolRakyat",
    seoDescription: "Match bank transactions to receipt records by amount and date. Find unmatched items and export reconciliation reports.",
  },
  {
    id: "akaunkemas-accountant-pack",
    name: "Accountant Pack",
    slug: "accountant-pack",
    categoryId: "akaunkemas",
    category: "AkaunKemas",
    description: "Generate a complete ZIP package for your accountant with cleaned transactions, receipt list, monthly summary, and PDF report.",
    icon: "Package",
    tags: ["accountant", "zip", "sme", "export", "akaunkemas", "pdf"],
    isImplemented: true,
    isPopular: true,
    route: "/tools/akaunkemas/accountant-pack",
    acceptedFileTypes: ["text/csv", "application/json"],
    maxFileSizeMB: 25,
    privacyNote: "All files are processed and packaged locally in your browser. Nothing is uploaded or stored.",
    seoTitle: "Accountant Pack — AkaunKemas | ToolRakyat",
    seoDescription: "Generate a complete accountant submission package as a ZIP file. Includes cleaned CSV, receipt list, summary JSON, and PDF report.",
  },
  {
    id: "akaunkemas-simple-ledger",
    name: "Simple Ledger",
    slug: "simple-ledger",
    categoryId: "akaunkemas",
    category: "AkaunKemas",
    description: "View cleaned transactions as a cashbook ledger with running balance, month/category filters, and export to CSV, JSON, or PDF.",
    icon: "BookOpen",
    tags: ["ledger", "cashbook", "sme", "akaunkemas", "export", "pdf"],
    isImplemented: true,
    isPopular: false,
    route: "/tools/akaunkemas/simple-ledger",
    acceptedFileTypes: ["text/csv"],
    maxFileSizeMB: 25,
    privacyNote: "All data is processed locally in your browser. Your financial data is never uploaded or stored.",
    seoTitle: "Simple Ledger — AkaunKemas | ToolRakyat",
    seoDescription: "View your SME transactions as a simple cashbook ledger with running balance, filters, and export options.",
  },
] satisfies ToolDefinition[];

export function getToolByCategoryAndSlug(
  categoryId: ToolCategoryId,
  slug: string,
) {
  return tools.find((t) => t.categoryId === categoryId && t.slug === slug);
}

export function getToolsByCategory(categoryId: ToolCategoryId) {
  return tools.filter((t) => t.categoryId === categoryId);
}

export function getPopularTools(limit = 12) {
  return tools.filter((t) => t.isPopular).slice(0, limit);
}

export function getCategoryLabel(categoryId: ToolCategoryId) {
  const found = TOOL_CATEGORIES.find((c) => c.id === categoryId);
  return found?.label ?? categoryId;
}
