/// Explicit appearance status resulting from a mutation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AppearanceStatus {
    /// Field logical value `/V` updated without appearance stream modification.
    ValueUpdated,
    /// Field and widget state `/AS` updated (e.g. checkbox or radio button toggle).
    StateUpdated,
    /// Appearance stream `/AP /N` was generated/regenerated by StarPDF.
    AppearanceRegenerated,
    /// Existing appearance stream `/AP /N` was preserved as-is.
    AppearancePreserved,
    /// Appearance generation was unsupported for this field configuration.
    AppearanceUnsupported,
}

impl AppearanceStatus {
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::ValueUpdated => "VALUE_UPDATED",
            Self::StateUpdated => "STATE_UPDATED",
            Self::AppearanceRegenerated => "APPEARANCE_REGENERATED",
            Self::AppearancePreserved => "APPEARANCE_PRESERVED",
            Self::AppearanceUnsupported => "APPEARANCE_UNSUPPORTED",
        }
    }

    /// Combines statuses for an atomic batch without losing a stronger outcome.
    pub const fn combine(self, other: Self) -> Self {
        if self.rank() >= other.rank() {
            self
        } else {
            other
        }
    }

    const fn rank(self) -> u8 {
        match self {
            Self::AppearancePreserved => 0,
            Self::ValueUpdated => 1,
            Self::StateUpdated => 2,
            Self::AppearanceRegenerated => 3,
            Self::AppearanceUnsupported => 4,
        }
    }
}
